spring.config.import=optional:file:/data/erp/config/env-prod.properties
spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}
resource.prefix=
spring.mvc.async.request-timeout=7200s

######### session ############
spring.session.timeout=PT10H

# spring session
spring.session.store-type=none
spring.cache.type=none
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

######### session ############
logging.level.root=INFO
logging.level.org.mybatis=DEBUG
logging.level.net.haion=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.from=${MAIL_SMTP_FROM}
spring.mail.properties.mail.smtp.localhost=${MAIL_SMTP_LOCALHOST}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ehlo=false

logging.level.org.springframework.mail=DEBUG

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

spring.batch.jdbc.initialize-schema=${BATCH_INITIALIZE_SCHEMA}
spring.batch.job.enabled=${BATCH_JOB_ENABLED:false}
spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

spring.jackson.time-zone=Asia/Seoul
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# Asterisk Settings
asterisk.host=${ASTERISK_HOST}
asterisk.port=${ASTERISK_PORT:5038}
asterisk.username=${ASTERISK_USERNAME:admin}
asterisk.password=${ASTERISK_PASSWORD:gkdldhs12#$}

######### Google Gemini AI Settings ############
google.ai.gemini.api-key=${GEMINI_API_KEY:AIzaSyCDvUwDSjNpqesOpFVEXzC7EH910Dg3ptk}
google.ai.gemini.model-name=gemini-1.5-pro

######### Chatwoot SSO Settings ############
chatwoot.api.url=${CHATWOOT_URL:http://localhost:3000}
chatwoot.account.id=${CHATWOOT_ACCOUNT_ID:1}
chatwoot.inbox.id=${CHATWOOT_INBOX_ID:1}
chatwoot.access.token=${CHATWOOT_ACCESS_TOKEN:FvDEbYNM16jAJGY9hZQ1ymvY}

######### 💡 MS-SQL (원가 데모용) 운영 서버 연동 설정 ############
THE_DB_HOST=${THE_DB_HOST:127.0.0.1}
THE_DB_PORT=${THE_DB_PORT:1433}
THE_DB_NAME=${THE_DB_NAME:SMARTDB}
THE_DB_USERNAME=${THE_DB_USERNAME:sa}
THE_DB_PASSWORD=${THE_DB_PASSWORD:crmbank}
THE_DB_INSTANCE=${THE_DB_INSTANCE:SQLEXPRESS}

logging.level.org.asteriskjava.manager.internal.ResponseBuilderImpl=ERROR
logging.level.org.asteriskjava.manager.internal.EventBuilderImpl=ERROR
